services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend
    container_name: backend
    restart: always
    command: /bin/sh -c "sleep 5 &&
      venv/bin/python manage.py makemigrations --noinput &&
      venv/bin/python manage.py migrate --noinput && 
      venv/bin/python manage.py collectstatic --noinput &&
      venv/bin/daphne -b 0.0.0.0 -p 8080 pong.asgi:application"
    volumes:
      - pong:/transcendence/pong
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    volumes:
      - pong_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pong:
    driver: local
    driver_opts:
      type: none
      device: ${PROJECT_PATH}
      o: bind
  pong_pg_data:
    driver: local

networks:
  app-network:
    driver: bridge
