# Generated by Django 5.1.1 on 2024-09-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_match_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournoi',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
